spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/bar-menu-v2
    password: mo45310914
  jpa:
    open-in-view: 'false'
    generate-ddl: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  thymeleaf:
    cache: 'false '
server:
  port: '8080'
