spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bar_menu?serverTimezone=UTC&characterEncoding=UTF-8
    username: localuser
    password: '0000'
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: 'true'
    show-sql: 'true'
  thymeleaf:
    cache: 'false '
